---
# tasks file for aervits.oozie

  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: git, maven, unzip

  - name: download oozie source release
    git:
      repo: 'https://github.com/apache/oozie.git'
      dest: "/tmp/{{ oozie_branch_version }}"
      force: yes
      version: "{{ oozie_branch_version }}"

  - name: compile oozie from source
    command: "/tmp/{{ oozie_branch_version }}/bin/mkdistro.sh -Dhadoop.version={{ hadoop_version }} -DskipTests=true"
    args:
      creates: "/tmp/{{ oozie_branch_version }}/distro/target/oozie-{{ oozie_version }}-distro.tar.gz"

  - name: change oozie tmp directory ownership
    file:
      path: "/tmp/{{ oozie_branch_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes

  - name: create oozie directory
    file:
      path: "/opt/oozie/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: extract oozie release
    unarchive:
      src: "/tmp/{{ oozie_branch_version }}/distro/target/oozie-{{ oozie_version }}-distro.tar.gz"
      dest: "/opt/oozie/{{ oozie_version }}"
      remote_src: yes
      keep_newer: yes
      creates: "/opt/oozie/{{ oozie_version }}/oozie-{{ oozie_version }}"

  - name: change oozie directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
    
  - name: export OOZIE_HOME
    lineinfile:
      path: /etc/environment
      line: export OOZIE_HOME="/opt/oozie/{{ oozie_version }}/oozie-{{ oozie_version }}"
      state: present
      create: yes

  - name: alias oozie command
    lineinfile:
      path: /etc/bashrc
      line: alias oozie=$OOZIE_HOME/bin/oozie
      state: present
      create: yes

  - name: create libext directory
    file:
      path: "$OOZIE_HOME/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: get jars for libext
    command: "find /tmp/{{ oozie_branch_version }}/server/target/dependency -type f"
    register: libext_jars

  - name: copy hadoop jars into libext directory
    copy:
      src: "{{ item }}"
      dest: "$OOZIE_HOME/libext"
      owner: oozie
      group: oozie
      mode: 0775
      remote_src: yes
    with_items:
      - "{{ libext_jars.stdout_lines }}"

  - name: download extjs and place in libext
    get_url:
      url: http://archive.cloudera.com/gplextras/misc/ext-2.2.zip
      dest: $OOZIE_HOME/libext

  - name: change oozie libext directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-{{ oozie_version }}/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
