---
# tasks file for aervits.oozie

  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: git, maven

  - name: download oozie source release
    git:
      repo: 'https://github.com/apache/oozie.git'
      dest: "/tmp/{{ oozie_version }}"
      force: yes
      version: "{{ oozie_version }}"

  - name: compile oozie from source
    command: "/tmp/{{ oozie_version }}/bin/mkdistro.sh -Dhadoop.version={{ hadoop_version }} -DskipTests=true"
    args:
      creates: "/tmp/{{ oozie_version }}/distro/oozie-5.0.0-beta1-distro.bin.tar.gz"

  - name: change oozie tmp directory ownership
    file:
      path: "/tmp/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes

  - name: create oozie directory
    file:
      path: "/opt/oozie/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: extract oozie release
    unarchive:
      src: "/tmp/{{ oozie_version }}/distro/target/oozie-5.0.0-beta1-distro.tar.gz"
      dest: "/opt/oozie/{{ oozie_version }}"
      remote_src: yes
      keep_newer: yes
      creates: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"

  - name: change oozie directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
    
  - name: export OOZIE_HOME
    lineinfile:
      path: /etc/environment
      line: export OOZIE_HOME="/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: present
      create: yes

  - name: alias oozie command
    lineinfile:
      path: /etc/bashrc
      line: alias oozie=$OOZIE_HOME/bin/oozie
      state: present
      create: yes

  - name: create libext directory
    file:
      path: "$OOZIE_HOME/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

# NEEDS WORK
#  - name: copy hadoop jars into libext directory
#    copy:
#      src: "/tmp/master/server/target/dependency/{{ item }}"
#      dest: $OOZIE_HOME/libext
#      owner: oozie
#      group: oozie
#      mode: 0775
#    with_items: hadoop-client-2.7.4.jar, hadoop-common-2.7.4.jar
