---
# tasks file for aervits.oozie

  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: git, maven, unzip

  - name: download oozie source release
    git:
      repo: 'https://github.com/apache/oozie.git'
      dest: "/tmp/{{ oozie_version }}"
      force: yes
      version: "{{ oozie_version }}"

  - name: compile oozie from source
    command: "/tmp/{{ oozie_version }}/bin/mkdistro.sh -Dhadoop.version={{ hadoop_version }} -DskipTests=true"
    args:
      creates: "/tmp/{{ oozie_version }}/distro/target/oozie-5.0.0-beta1-distro.tar.gz"

  - name: change oozie tmp directory ownership
    file:
      path: "/tmp/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes

  - name: create oozie directory
    file:
      path: "/opt/oozie/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: extract oozie release
    unarchive:
      src: "/tmp/{{ oozie_version }}/distro/target/oozie-5.0.0-beta1-distro.tar.gz"
      dest: "/opt/oozie/{{ oozie_version }}"
      remote_src: yes
      keep_newer: yes
      creates: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"

  - name: change oozie directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
    
  - name: export OOZIE_HOME
    lineinfile:
      path: /etc/environment
      line: export OOZIE_HOME="/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: present
      create: yes

  - name: alias oozie command
    lineinfile:
      path: /etc/bashrc
      line: alias oozie=$OOZIE_HOME/bin/oozie
      state: present
      create: yes

  - name: create libext directory
    file:
      path: "$OOZIE_HOME/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: copy hadoop jars into libext directory
    copy:
      src: "/tmp/{{ oozie_version }}/server/target/dependency/{{ item }}"
      dest: "$OOZIE_HOME/libext/{{ item }}"
      owner: oozie
      group: oozie
      mode: 0775
      remote_src: yes
    with_items:
      - "hadoop-client-{{ hadoop_version }}.jar"
      - "hadoop-common-{{ hadoop_version }}.jar"
      - "hadoop-annotations-{{ hadoop_version }}.jar"
      - "hadoop-hdfs-{{ hadoop_version }}.jar"
      - "hadoop-auth-{{ hadoop_version }}.jar"
      - "hadoop-yarn-api-{{ hadoop_version }}.jar"
      - "hadoop-yarn-client-{{ hadoop_version }}.jar"
      - "hadoop-yarn-common-{{ hadoop_version }}.jar"
      - "hadoop-yarn-server-common-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-app-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-common-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-core-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-jobclient-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-shuffle-{{ hadoop_version }}.jar"
      - guava-11.0.2.jar
      - commons-collections-3.2.2.jar
      - commons-codec-1.4.jar

  - name: download extjs and place in libext
    get_url:
      url: http://archive.cloudera.com/gplextras/misc/ext-2.2.zip
      dest: $OOZIE_HOME/libext

  - name: change oozie libext directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
