---
# tasks file for aervits.oozie

  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: git, maven, unzip

  - name: download oozie source release
    git:
      repo: 'https://github.com/apache/oozie.git'
      dest: "/tmp/{{ oozie_version }}"
      force: yes
      version: "{{ oozie_version }}"

  - name: compile oozie from source
    command: "/tmp/{{ oozie_version }}/bin/mkdistro.sh -Dhadoop.version={{ hadoop_version }} -DskipTests=true"
    args:
      creates: "/tmp/{{ oozie_version }}/distro/target/oozie-5.0.0-beta1-distro.tar.gz"

  - name: change oozie tmp directory ownership
    file:
      path: "/tmp/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes

  - name: create oozie directory
    file:
      path: "/opt/oozie/{{ oozie_version }}"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: extract oozie release
    unarchive:
      src: "/tmp/{{ oozie_version }}/distro/target/oozie-5.0.0-beta1-distro.tar.gz"
      dest: "/opt/oozie/{{ oozie_version }}"
      remote_src: yes
      keep_newer: yes
      creates: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"

  - name: change oozie directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
    
  - name: export OOZIE_HOME
    lineinfile:
      path: /etc/environment
      line: export OOZIE_HOME="/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1"
      state: present
      create: yes

  - name: alias oozie command
    lineinfile:
      path: /etc/bashrc
      line: alias oozie=$OOZIE_HOME/bin/oozie
      state: present
      create: yes

  - name: create libext directory
    file:
      path: "$OOZIE_HOME/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: copy hadoop jars into libext directory
    copy:
      src: "/tmp/{{ oozie_version }}/server/target/dependency/{{ item }}"
      dest: "$OOZIE_HOME/libext/{{ item }}"
      owner: oozie
      group: oozie
      mode: 0775
      remote_src: yes
    with_items:
      - "hadoop-client-{{ hadoop_version }}.jar"
      - "hadoop-common-{{ hadoop_version }}.jar"
      - "hadoop-annotations-{{ hadoop_version }}.jar"
      - "hadoop-hdfs-{{ hadoop_version }}.jar"
      - "hadoop-auth-{{ hadoop_version }}.jar"
      - "hadoop-yarn-api-{{ hadoop_version }}.jar"
      - "hadoop-yarn-client-{{ hadoop_version }}.jar"
      - "hadoop-yarn-common-{{ hadoop_version }}.jar"
      - "hadoop-yarn-server-common-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-app-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-common-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-core-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-jobclient-{{ hadoop_version }}.jar"
      - "hadoop-mapreduce-client-shuffle-{{ hadoop_version }}.jar"
      - oozie-client-5.0.0-beta1.jar
      - oozie-core-5.0.0-beta1.jar
      - xercesImpl-2.11.0.jar
      - xml-apis-1.4.01.jar
      - xml-apis-ext-1.3.04.jar
      - guava-11.0.2.jar
      - commons-collections-3.2.2.jar
      - commons-codec-1.4.jar
      - commons-cli-1.2.jar
      - commons-logging-1.1.jar
      - derby-10.10.1.1.jar
      - jcl-over-slf4j-1.7.25.jar
      - jul-to-slf4j-1.7.25.jar
      - javax.servlet-api-3.1.0.jar
      - commons-el-1.0.jar
      - apache-log4j-extras-1.2.17.jar
      - apache-jsp-9.2.19.v20160908.jar
      - apache-jsp-8.0.33.jar
      - apache-el-8.0.33.jar
      - apacheds-kerberos-codec-2.0.0-M15.jar
      - apacheds-i18n-2.0.0-M15.jar
      - htrace-core-3.1.0-incubating.jar
      - protobuf-java-2.5.0.jar
      - asm-tree-5.0.1.jar
      - jsr305-3.0.0.jar
      - xmlgraphics-commons-2.2.jar
      - stringtemplate-3.2.1.jar
      - ST4-4.0.4.jar
      - jersey-core-1.9.jar
      - commons-dbcp-1.4.jar
      - jdk.tools-1.8.jar
      - commons-net-3.1.jar
      - jackson-jaxrs-1.8.3.jar
      - openjpa-jdbc-2.4.2.jar
      - commons-exec-1.3.jar
      - xbean-asm5-shaded-3.17.jar
      - snappy-java-1.0.4.1.jar
      - servlet-api-2.5.jar
      - openjpa-lib-2.4.2.jar
      - jets3t-0.9.0.jar
      - groovy-all-2.1.6.jar
      - datanucleus-core-3.2.10.jar
      - jaxb-impl-2.2.3-1.jar
      - httpclient-4.3.6.jar
      - antlr-2.7.7.jar
      - commons-math3-3.1.1.jar
      - jackson-mapper-asl-1.9.13.jar
      - jersey-server-1.9.jar
      - eigenbase-properties-1.1.5.jar
      - jdom-1.1.jar
      - commons-configuration-1.6.jar
      - commons-digester-1.8.jar
      - datanucleus-api-jdo-3.2.6.jar
      - slf4j-log4j12-1.6.6.jar
      - slf4j-api-1.6.6.jar
      - log4j-1.2.17.jar

  - name: download extjs and place in libext
    get_url:
      url: http://archive.cloudera.com/gplextras/misc/ext-2.2.zip
      dest: $OOZIE_HOME/libext

  - name: change oozie libext directory ownership
    file:
      path: "/opt/oozie/{{ oozie_version }}/oozie-5.0.0-beta1/libext"
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
      recurse: yes
