---
# tasks file for aervits.oozie

  - name: create oozie directory
    file:
      path: /opt/oozie
      state: directory
      owner: oozie
      group: oozie
      mode: 0775

  - name: oozie directory
    file:
      path: /opt/oozie
      state: directory
      owner: oozie
      group: oozie
      mode: 0775
 
  - name: download oozie source release
    git:
      repo: 'https://github.com/apache/oozie.git'
      dest: /opt/oozie
      version: master

  - name: compile oozie from source
    command: /opt/oozie/bin/mkdistro.sh -DskipTests=true
