---
- hosts: ambari-server
  remote_user: centos
  tasks:
  - name: download ambari repo
    get_url:
      url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.5.1.0/ambari.repo
      dest: /etc/yum.repos.d/ambari.repo
  - name: make sure ambari-server is latest
    yum:
      name: ambari-server
      state: latest
  - name: run ambari-server silent install
    shell: ambari-server setup -s
  - name: start ambari server
    service:
      name: ambari-server
      state: started
