---
- hosts: all
  remote_user: centos
  tasks:
  - name: download ambari repo
    get_url:
      url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.5.1.0/ambari.repo
      dest: /etc/yum.repos.d/ambari.repo
  - name: make sure ambari-agent is latest
    yum:
      name: ambari-agent
      state: latest
  - name: replace the default ambari-agent template with ambari-server name
    replace:
      path: /etc/ambari-agent/conf/ambari-agent.ini
      regexp: 'localhost'
      replace: 'aervits-hdp0.field.hortonworks.com'
      backup: yes
  - name: ensure ambari-agent is stopped
    service:
      name: ambari-agent
      state: stopped
  - name: start ambari-agent
    service:
      name: ambari-agent
      state: started
  handlers:
    - name: restart ambari-agent
      service:
        name: ambari-agent
        state: restarted
    - name: restart ambari-agent
      service:
        name: ambari-agent
        state: restarted
