---
- hosts: all
  remote_user: centos
  vars:
    users:
      - centos
      - guest
      - admin
  tasks:
  - name: make sure all host files match
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: wget, ntp, nscd, libselinux-python
  - name: ensure nptd is running
    service:
      name: ntpd
      state: started
  - name: ensure nscd is running
    service:
      name: nscd
      state: started
  - pam_limits:
      domain: root
      limit_type: hard
      limit_item: nproc
      value: 64000
      use_max: yes
  - pam_limits:
      domain: root
      limit_type: hard
      limit_item: nofile
      value: 64000
      use_max: yes
  - pam_limits:
      domain: root
      limit_type: soft
      limit_item: nproc
      value: 64000
      use_max: yes
  - pam_limits:
      domain: root
      limit_type: soft
      limit_item: nofile
      value: 64000
      use_max: yes
  - name: add unix user "{{ item }}"
    user:
      name: "{{ item }}"
      state: present
    with_items: "{{ users }}"
  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
    - name: restart nscd
      service:
        name: nscd
        state: restarted
