---
- hosts: all
  remote_user: centos
  tasks:
  - name: make sure all host files match
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  - name: make sure wget is latest
    yum:
      name: wget
      state: latest
  - name: make sure ntp is latest
    yum:
      name: ntp
      state: latest
  - name: make sure nscd is latest
    yum:
      name: nscd
      state: latest
  - name: ensure nptd is running
    service:
      name: ntpd
      state: started
  - name: ensure nscd is running
    service:
      name: nscd
      state: started
  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
    - name: restart nscd
      service:
        name: nscd
        state: restarted
