---
# tasks file for aervits.hosts
#  - debug: var=hostvars[inventory_hostname]
#  - debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']

  - name: update host name
    hostname:
      name: "{{ ansible_nodename }}"

  - name: update localhost
    lineinfile:
      path: "{{ hostname_hosts_file_location }}"
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4{{'\n'}}{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}{{ '   ' }}{{ ansible_fqdn }}{{ '   '}}{{ ansible_nodename }}"
      state: present
#      insertafter: EOF
      backup: yes
      owner: root
      group: root
      mode: 0644
