---
# tasks file for aervits.users
  - name: add service user "{{ item }}"
    user:
      name: "{{ item }}"
      comment: "{{ item }} service user"
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa
      ssh_key_comment: "passwordless ssh"
      ssh_key_passphrase:
      ssh_key_type: rsa
    with_items: "{{ service_users }}"

  - name: get JAVA_HOME
    shell: "dirname $(dirname $(readlink -f $(which javac)))"
    register: JAVA_HOME

  - name: export JAVA_HOME
    lineinfile:
      path: /etc/environment
      line: "export JAVA_HOME={{ JAVA_HOME.stdout }}"
      state: present
      create: yes
