---
- hosts: all
  roles:
    - aervits.jdk
    - aervits.ssh
    - aervits.users
    - aervits.hadoop
    - aervits.hbase
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - hbase
       - hadoop
       - vagrant
