---
- hosts: all
  roles:
    - aervits.jdk
    - aervits.ssh
    - aervits.users
    - aervits.hadoop
    - aervits.git
    - aervits.mvn
    - aervits.oozie
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - oozie
       - hadoop
       - vagrant
