---
# defaults file for aervits.hbase
  hbase_version: "hbase-2.0.0-alpha4"
  hbase_url: http://mirror.stjschools.org/public/apache/hbase/2.0.0-alpha4/hbase-2.0.0-alpha4-bin.tar.gz
  hbase_md5_sum: 5E117E07294C70B39A7AFF4BBCFC2EE0
