---
# tasks file for aervits.ambari-agent
  - name: download ambari repo
    get_url:
      url: "{{ ambari_repo }}"
      dest: /etc/yum.repos.d/ambari.repo
      force: yes
  - name: make sure ambari packages are the latest
    yum:
      name: ambari*
      state: latest
  - name: replace the default ambari-agent template with ambari-server name
    replace:
      path: /etc/ambari-agent/conf/ambari-agent.ini
      regexp: 'localhost'
      replace: "{{ ambari_server_hostname }}"
      backup: yes
